# Generated by Django 4.2 on 2024-06-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-priority', 'id']},
        ),
    ]
