# Generated by Django 4.2 on 2024-06-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_childs',
            field=models.CharField(choices=[('all', 'All Categories'), ('none', 'Display No Childs'), ('general', 'General Category'), ('brand', 'Brand Category'), ('feature', 'Feature Category'), ('tag', 'Tag Under Feature')], default='none', max_length=20),
        ),
    ]
