# Generated by Django 4.2 on 2024-07-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0006_alter_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specificationtable',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='specification',
            name='aliases',
            field=models.ManyToManyField(blank=True, related_name='specs', to='hificom.titlealias'),
        ),
        migrations.AlterField(
            model_name='specificationtable',
            name='aliases',
            field=models.ManyToManyField(blank=True, related_name='tables', to='hificom.titlealias'),
        ),
    ]
