# Generated by Django 4.2 on 2024-07-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0007_alter_specificationtable_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='keyfeature',
            name='value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
