# Generated by Django 4.2 on 2024-07-12 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0009_remove_product_model_alter_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_type',
            field=models.CharField(choices=[('general', 'General Category'), ('brand', 'Brand Category'), ('series', 'Series Category'), ('feature', 'Feature Category'), ('tag', 'Tag Under Feature')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='display_childs',
            field=models.CharField(choices=[('all', 'All Categories'), ('none', 'Display No Childs'), ('general', 'General Category'), ('brand', 'Brand Category'), ('series', 'Series Category'), ('feature', 'Feature Category'), ('tag', 'Tag Under Feature')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(related_name='groups', to='hificom.category')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hificom.category')),
            ],
        ),
    ]
