# Generated by Django 4.2 on 2024-07-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0010_alter_category_cat_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygroup',
            name='slug',
            field=models.SlugField(default='foo', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorygroup',
            name='title',
            field=models.CharField(default='bar', max_length=200),
            preserve_default=False,
        ),
    ]
