# Generated by Django 4.2 on 2024-07-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0011_categorygroup_slug_categorygroup_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorygroup',
            options={'ordering': ['-priority', 'id']},
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_type',
            field=models.CharField(choices=[('general', 'General Category'), ('brand', 'Brand Category'), ('series', 'Series Category'), ('feature', 'Feature Category'), ('tag', 'Tag')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='display_childs',
            field=models.CharField(choices=[('all', 'All Categories'), ('none', 'Display No Childs'), ('general', 'General Category'), ('brand', 'Brand Category'), ('series', 'Series Category'), ('feature', 'Feature Category'), ('tag', 'Tag')], default='none', max_length=20),
        ),
    ]
