# Generated by Django 4.2 on 2024-07-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0015_alter_product_rating_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(db_index=True, max_length=100)),
                ('priority', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(related_name='collections', to='hificom.product')),
            ],
            options={
                'ordering': ['-priority', 'id'],
            },
        ),
    ]
