# Generated by Django 4.2 on 2024-07-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0018_alter_productcollection_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='link',
        ),
        migrations.AddField(
            model_name='carousel',
            name='site_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
