# Generated by Django 4.2 on 2024-07-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0019_remove_carousel_link_carousel_site_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='main',
            field=models.ImageField(max_length=500, upload_to='product/main'),
        ),
    ]
