# Generated by Django 4.2 on 2024-07-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0020_alter_productimage_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='value',
            field=models.CharField(max_length=10000),
        ),
    ]
