# Generated by Django 4.2 on 2024-08-08 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hificom.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hificom', '0021_alter_category_description_alter_productspec_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartid', models.CharField(db_index=True, default=hificom.models.hexcode_gen, max_length=50, unique=True)),
                ('checked_out', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hificom.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hificom.product')),
            ],
        ),
    ]
