# Generated by Django 4.2 on 2024-08-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0022_cart_cartproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ip_address',
        ),
    ]
