# Generated by Django 4.2 on 2024-08-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0023_remove_cart_ip_address'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartproduct',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_product_in_cart'),
        ),
    ]
