# Generated by Django 4.2 on 2024-08-15 09:07

from django.db import migrations, models
import django.db.models.deletion
import hificom.models


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0026_cart_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hificom.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='oid',
            field=models.CharField(db_index=True, default=hificom.models.hexcode_gen, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payable',
            field=models.FloatField(default=0),
        ),
    ]
