# Generated by Django 4.2 on 2024-10-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0030_alter_order_options_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
