# Generated by Django 4.2 on 2025-03-08 10:37

from django.db import migrations, models
import hificom.models


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0031_alter_order_added_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['-priority', '-added_at']},
        ),
        migrations.AddField(
            model_name='carousel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(default=hificom.models.get_banner_title, max_length=200),
        ),
    ]
