# Generated by Django 4.2 on 2025-03-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0034_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('replied', 'Replied')], default='pending', max_length=20),
        ),
    ]
