# Generated by Django 4.2 on 2025-03-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0035_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
