MAIN_CATEGORIES = [
    {
        'title': 'Laptop',
        'slug': 'laptop',
        'priority': 10,
        'get_features_from_child': True,
        'seo_title': 'Laptops at HiFi Computer',
        'description': 'Discover a wide range of laptops at HiFi Computer, featuring top brands and models for every need. Whether you need a laptop for gaming, business, or everyday use, find the perfect device at competitive prices. Enjoy doorstep delivery and unbeatable discounts on laptops across Bangladesh.',
    },
    {
        'title': 'Desktop',
        'slug': 'desktop',
        'priority': 9,
        'get_features_from_child': True,
        'seo_title': 'Desktops at HiFi Computer',
        'description': 'Explore powerful desktop computers at HiFi Computer, designed for gaming, professional use, and more. Discover reliable brands and customizable options at competitive prices in Bangladesh. Benefit from doorstep delivery and exclusive discounts on desktops.',
    },
    {
        'title': 'PC Component',
        'slug': 'pc-component',
        'priority': 8,
        'seo_title': 'PC Components at HiFi Computer',
        'description': 'Find essential PC components and upgrades at HiFi Computer. Browse a wide selection of processors, graphics cards, RAM, and more to build or upgrade your PC. Enjoy competitive prices and doorstep delivery on PC components across Bangladesh.',
    },
    {
        'title': 'Monitor',
        'slug': 'monitor',
        'priority': 7,
        'get_features_from_child': True,
        'seo_title': 'Monitors at HiFi Computer',
        'description': 'Discover high-quality monitors at HiFi Computer, perfect for gaming, productivity, and creative tasks. Explore a variety of sizes and resolutions from top brands at competitive prices in Bangladesh. Enjoy doorstep delivery and special discounts on monitors.',
    },
    {
        'title': 'Accessories',
        'slug': 'accessories',
        'priority': 6,
        'seo_title': 'Computer Accessories at HiFi Computer',
        'description': 'Complete your setup with computer accessories from HiFi Computer. Explore a wide range of keyboards, mice, adapters, and more at competitive prices in Bangladesh. Benefit from doorstep delivery and find all the accessories you need in one place.',
    },
    {
        'title': 'Networking',
        'slug': 'networking',
        'priority': 5,
        'seo_title': 'Networking Equipment at HiFi Computer',
        'description': 'Enhance your connectivity with networking equipment from HiFi Computer. Discover routers, switches, extenders, and cables from top brands at competitive prices in Bangladesh. Enjoy doorstep delivery and build a reliable network with our range of networking solutions.',
    },
    {
        'title': 'Printer',
        'slug': 'printer',
        'priority': 4,
        'get_features_from_child': True,
        'seo_title': 'Printers at HiFi Computer',
        'description': 'Shop for printers at HiFi Computer, offering a variety of models for home and office use. Find reliable brands and multifunction printers at competitive prices in Bangladesh. Enjoy doorstep delivery and explore our selection of printers to find the perfect fit for your needs.',
    },
    {
        'title': 'Office Equipment',
        'slug': 'office-equipment',
        'priority': 3,
        'seo_title': 'Office Equipment at HiFi Computer',
        'description': 'Equip your office with essential equipment from HiFi Computer. Explore scanners, shredders, projectors, and more at competitive prices in Bangladesh. Enjoy doorstep delivery and streamline your office operations with our range of office equipment.',
    },
    {
        'title': 'Sound System',
        'slug': 'sound-system',
        'priority': 2,
        'seo_title': 'Sound Systems at HiFi Computer',
        'description': 'Immerse yourself in superior sound with sound systems from HiFi Computer. Discover speakers, headphones, soundbars, and more from top brands at competitive prices in Bangladesh. Enjoy doorstep delivery and enhance your audio experience with our range of sound systems.',
    },
    {
        'title': 'Software',
        'slug': 'software',
        'priority': 1,
        'seo_title': 'Software at HiFi Computer',
        'description': 'Explore essential software solutions at HiFi Computer, including operating systems, productivity software, security suites, and more. Find trusted brands and competitive prices in Bangladesh. Enjoy doorstep delivery and secure your devices with our range of software.',
    },
]
