cpu_cooler_brands = [
    {
        'title': 'First Player',
        'slug': 'first-player-cpu-cooler',
        'priority': 4,
        'seo_title': 'First Player CPU Coolers at HiFi Computer',
        'description': 'Explore First Player CPU coolers offering efficient cooling solutions for gaming and performance systems.',
        'cat_type': 'brand',
    },
    {
        'title': 'Antec',
        'slug': 'antec-cpu-cooler',
        'priority': 4,
        'seo_title': 'Antec CPU Coolers at HiFi Computer',
        'description': 'Discover Antec CPU coolers designed to provide high-quality cooling performance for enthusiasts and gamers.',
        'cat_type': 'brand',
    },
    {
        'title': 'Arctic',
        'slug': 'arctic-cpu-cooler',
        'priority': 4,
        'seo_title': 'Arctic CPU Coolers at HiFi Computer',
        'description': 'Find Arctic CPU coolers offering quiet, efficient cooling for performance and overclocked builds.',
        'cat_type': 'brand',
    },
    {
        'title': 'ASUS',
        'slug': 'asus-cpu-cooler',
        'priority': 4,
        'seo_title': 'ASUS CPU Coolers at HiFi Computer',
        'description': 'Check out ASUS CPU coolers for superior cooling efficiency and sleek design, perfect for gaming setups.',
        'cat_type': 'brand',
    },
    {
        'title': 'Cooler Master',
        'slug': 'cooler-master-cpu-cooler',
        'priority': 4,
        'seo_title': 'Cooler Master CPU Coolers at HiFi Computer',
        'description': 'Explore Cooler Master CPU coolers, known for their high-performance air and liquid cooling solutions.',
        'cat_type': 'brand',
    },
    {
        'title': 'Corsair',
        'slug': 'corsair-cpu-cooler',
        'priority': 4,
        'seo_title': 'Corsair CPU Coolers at HiFi Computer',
        'description': 'Discover Corsair CPU coolers designed for extreme performance, perfect for gaming and overclocking.',
        'cat_type': 'brand',
    },
    {
        'title': 'Deepcool',
        'slug': 'deepcool-cpu-cooler',
        'priority': 4,
        'seo_title': 'Deepcool CPU Coolers at HiFi Computer',
        'description': 'Browse Deepcool CPU coolers offering exceptional cooling performance for gaming and professional setups.',
        'cat_type': 'brand',
    },
    {
        'title': 'Gamdias',
        'slug': 'gamdias-cpu-cooler',
        'priority': 4,
        'seo_title': 'Gamdias CPU Coolers at HiFi Computer',
        'description': 'Discover Gamdias CPU coolers known for their innovative designs and reliable cooling technology.',
        'cat_type': 'brand',
    },
    {
        'title': 'Gigabyte',
        'slug': 'gigabyte-cpu-cooler',
        'priority': 4,
        'seo_title': 'Gigabyte CPU Coolers at HiFi Computer',
        'description': 'Explore Gigabyte CPU coolers designed to deliver efficient cooling and seamless compatibility with gaming PCs.',
        'cat_type': 'brand',
    },
    {
        'title': 'Lian Li',
        'slug': 'lian-li-cpu-cooler',
        'priority': 4,
        'seo_title': 'Lian Li CPU Coolers at HiFi Computer',
        'description': 'Check out Lian Li CPU coolers, offering a sleek aesthetic and robust cooling performance for high-end builds.',
        'cat_type': 'brand',
    },
    {
        'title': 'Montech',
        'slug': 'montech-cpu-cooler',
        'priority': 4,
        'seo_title': 'Montech CPU Coolers at HiFi Computer',
        'description': 'Discover Montech CPU coolers that offer efficient thermal solutions and modern designs for all types of users.',
        'cat_type': 'brand',
    },
    {
        'title': 'NZXT',
        'slug': 'nzxt-cpu-cooler',
        'priority': 4,
        'seo_title': 'NZXT CPU Coolers at HiFi Computer',
        'description': 'Find NZXT CPU coolers known for their stylish designs and superior liquid cooling technology.',
        'cat_type': 'brand',
    },
    {
        'title': 'PC Cooler',
        'slug': 'pc-cooler-cpu-cooler',
        'priority': 4,
        'seo_title': 'PC Cooler CPU Coolers at HiFi Computer',
        'description': 'Browse PC Cooler brand CPU coolers offering affordable, efficient cooling solutions for various builds.',
        'cat_type': 'brand',
    },
    {
        'title': 'Redragon',
        'slug': 'redragon-cpu-cooler',
        'priority': 4,
        'seo_title': 'Redragon CPU Coolers at HiFi Computer',
        'description': 'Explore Redragon CPU coolers designed for gaming enthusiasts looking for performance and style.',
        'cat_type': 'brand',
    },
    {
        'title': 'Team',
        'slug': 'team-cpu-cooler',
        'priority': 4,
        'seo_title': 'Team CPU Coolers at HiFi Computer',
        'description': 'Check out Team CPU coolers offering competitive performance and reliability for mainstream users.',
        'cat_type': 'brand',
    },
    {
        'title': 'Thermalright',
        'slug': 'thermalright-cpu-cooler',
        'priority': 4,
        'seo_title': 'Thermalright CPU Coolers at HiFi Computer',
        'description': 'Discover Thermalright CPU coolers delivering exceptional thermal management for both gaming and professional builds.',
        'cat_type': 'brand',
    },
    {
        'title': 'Thermaltake',
        'slug': 'thermaltake-cpu-cooler',
        'priority': 4,
        'seo_title': 'Thermaltake CPU Coolers at HiFi Computer',
        'description': 'Find Thermaltake CPU coolers known for their powerful cooling systems, ideal for gamers and PC enthusiasts.',
        'cat_type': 'brand',
    },
    {
        'title': 'Value Top',
        'slug': 'value-top-cpu-cooler',
        'priority': 4,
        'seo_title': 'Value Top CPU Coolers at HiFi Computer',
        'description': 'Explore Value Top CPU coolers that provide cost-effective cooling solutions without compromising performance.',
        'cat_type': 'brand',
    },
    {
        'title': 'Xigmatek',
        'slug': 'xigmatek-cpu-cooler',
        'priority': 4,
        'seo_title': 'Xigmatek CPU Coolers at HiFi Computer',
        'description': 'Discover Xigmatek CPU coolers offering high-performance and reliability for gamers and overclockers.',
        'cat_type': 'brand',
    },
    {
        'title': 'Xtreme',
        'slug': 'xtreme-cpu-cooler',
        'priority': 4,
        'seo_title': 'Xtreme CPU Coolers at HiFi Computer',
        'description': 'Browse Xtreme CPU coolers, designed to offer excellent cooling performance for high-demand systems.',
        'cat_type': 'brand',
    },
]

cpu_cooler_types = [
    {
        'title': 'Air Cooler',
        'slug': 'air-cpu-cooler',
        'priority': 4,
        'seo_title': 'Air CPU Coolers at HiFi Computer',
        'description': 'Explore air CPU coolers that provide efficient cooling with effective airflow for gaming and performance systems.',
        'cat_type': 'tag',
    },
    {
        'title': 'CPU Water Block',
        'slug': 'cpu-water-block-cpu-cooler',
        'priority': 4,
        'seo_title': 'CPU Water Blocks at HiFi Computer',
        'description': 'Discover CPU water blocks designed to work with liquid cooling systems for superior thermal performance.',
        'cat_type': 'tag',
    },
    {
        'title': 'Liquid Cooler',
        'slug': 'liquid-cpu-cooler',
        'priority': 4,
        'seo_title': 'Liquid CPU Coolers at HiFi Computer',
        'description': 'Find liquid CPU coolers offering efficient cooling solutions with minimal noise for high-performance systems.',
        'cat_type': 'tag',
    },
    {
        'title': 'Water Cooling Kit',
        'slug': 'water-cooling-kit-cpu-cooler',
        'priority': 4,
        'seo_title': 'Water Cooling Kits at HiFi Computer',
        'description': 'Browse comprehensive water cooling kits that provide everything needed for optimal cooling performance.',
        'cat_type': 'tag',
    },
]

supported_cpu_socket_brand = [
    {
        'title': 'Intel',
        'slug': 'intel-cpu-cooler',
        'priority': 4,
        'seo_title': 'Intel CPU Coolers at HiFi Computer',
        'description': 'Explore a variety of Intel CPU coolers designed for efficient cooling and optimal performance in your Intel-based systems.',
        'cat_type': 'tag',
    },
    {
        'title': 'Ryzen',
        'slug': 'ryzen-cpu-cooler',
        'priority': 4,
        'seo_title': 'Ryzen CPU Coolers at HiFi Computer',
        'description': 'Discover high-performance Ryzen CPU coolers tailored for AMD Ryzen processors, ensuring effective thermal management.',
        'cat_type': 'tag',
    },
]

fan_speed = [
    {
        'title': '1200 RPM',
        'slug': 'cpu-cooler-1200-rpm',
        'priority': 4,
        'seo_title': '1200 RPM CPU Coolers at HiFi Computer',
        'description': 'Find CPU coolers operating at 1200 RPM for efficient cooling and low noise levels.',
        'cat_type': 'tag',
    },
    {
        'title': '1400 RPM',
        'slug': 'cpu-cooler-1400-rpm',
        'priority': 4,
        'seo_title': '1400 RPM CPU Coolers at HiFi Computer',
        'description': 'Explore CPU coolers with a speed of 1400 RPM, providing a balance between cooling performance and noise.',
        'cat_type': 'tag',
    },
    {
        'title': '1500 RPM',
        'slug': 'cpu-cooler-1500-rpm',
        'priority': 4,
        'seo_title': '1500 RPM CPU Coolers at HiFi Computer',
        'description': 'Discover CPU coolers that run at 1500 RPM for optimal cooling efficiency.',
        'cat_type': 'tag',
    },
    {
        'title': '1550 RPM',
        'slug': 'cpu-cooler-1550-rpm',
        'priority': 4,
        'seo_title': '1550 RPM CPU Coolers at HiFi Computer',
        'description': 'Browse 1550 RPM CPU coolers, designed for effective heat dissipation.',
        'cat_type': 'tag',
    },
    {
        'title': '1600 RPM',
        'slug': 'cpu-cooler-1600-rpm',
        'priority': 4,
        'seo_title': '1600 RPM CPU Coolers at HiFi Computer',
        'description': 'Check out CPU coolers with a speed of 1600 RPM for reliable cooling performance.',
        'cat_type': 'tag',
    },
    {
        'title': '1700 RPM',
        'slug': 'cpu-cooler-1700-rpm',
        'priority': 4,
        'seo_title': '1700 RPM CPU Coolers at HiFi Computer',
        'description': 'Find CPU coolers operating at 1700 RPM, suitable for demanding applications.',
        'cat_type': 'tag',
    },
    {
        'title': '1750 RPM',
        'slug': 'cpu-cooler-1750-rpm',
        'priority': 4,
        'seo_title': '1750 RPM CPU Coolers at HiFi Computer',
        'description': 'Explore 1750 RPM CPU coolers for efficient cooling without excessive noise.',
        'cat_type': 'tag',
    },
    {
        'title': '1800 RPM',
        'slug': 'cpu-cooler-1800-rpm',
        'priority': 4,
        'seo_title': '1800 RPM CPU Coolers at HiFi Computer',
        'description': 'Discover CPU coolers with a fan speed of 1800 RPM for optimal thermal management.',
        'cat_type': 'tag',
    },
    {
        'title': '1850 RPM',
        'slug': 'cpu-cooler-1850-rpm',
        'priority': 4,
        'seo_title': '1850 RPM CPU Coolers at HiFi Computer',
        'description': 'Browse CPU coolers operating at 1850 RPM, ideal for high-performance systems.',
        'cat_type': 'tag',
    },
    {
        'title': '1900 RPM',
        'slug': 'cpu-cooler-1900-rpm',
        'priority': 4,
        'seo_title': '1900 RPM CPU Coolers at HiFi Computer',
        'description': 'Find efficient CPU coolers with a fan speed of 1900 RPM.',
        'cat_type': 'tag',
    },
    {
        'title': '1950 RPM',
        'slug': 'cpu-cooler-1950-rpm',
        'priority': 4,
        'seo_title': '1950 RPM CPU Coolers at HiFi Computer',
        'description': 'Explore 1950 RPM CPU coolers for effective cooling solutions.',
        'cat_type': 'tag',
    },
    {
        'title': '2000 RPM',
        'slug': 'cpu-cooler-2000-rpm',
        'priority': 4,
        'seo_title': '2000 RPM CPU Coolers at HiFi Computer',
        'description': 'Discover CPU coolers with a fan speed of 2000 RPM for robust thermal performance.',
        'cat_type': 'tag',
    },
    {
        'title': '2100 RPM',
        'slug': 'cpu-cooler-2100-rpm',
        'priority': 4,
        'seo_title': '2100 RPM CPU Coolers at HiFi Computer',
        'description': 'Browse 2100 RPM CPU coolers designed for high-performance cooling.',
        'cat_type': 'tag',
    },
    {
        'title': '2150 RPM',
        'slug': 'cpu-cooler-2150-rpm',
        'priority': 4,
        'seo_title': '2150 RPM CPU Coolers at HiFi Computer',
        'description': 'Find CPU coolers operating at 2150 RPM for efficient heat dissipation.',
        'cat_type': 'tag',
    },
    {
        'title': '2200 RPM',
        'slug': 'cpu-cooler-2200-rpm',
        'priority': 4,
        'seo_title': '2200 RPM CPU Coolers at HiFi Computer',
        'description': 'Explore CPU coolers with a speed of 2200 RPM for optimal cooling performance.',
        'cat_type': 'tag',
    },
    {
        'title': '2250 RPM',
        'slug': 'cpu-cooler-2250-rpm',
        'priority': 4,
        'seo_title': '2250 RPM CPU Coolers at HiFi Computer',
        'description': 'Discover CPU coolers operating at 2250 RPM, ensuring effective thermal management.',
        'cat_type': 'tag',
    },
    {
        'title': '2300 RPM',
        'slug': 'cpu-cooler-2300-rpm',
        'priority': 4,
        'seo_title': '2300 RPM CPU Coolers at HiFi Computer',
        'description': 'Find CPU coolers with a fan speed of 2300 RPM for enhanced cooling performance.',
        'cat_type': 'tag',
    },
    {
        'title': '2400 RPM',
        'slug': 'cpu-cooler-2400-rpm',
        'priority': 4,
        'seo_title': '2400 RPM CPU Coolers at HiFi Computer',
        'description': 'Explore CPU coolers operating at 2400 RPM, perfect for high-demand applications.',
        'cat_type': 'tag',
    },
    {
        'title': '2500 RPM',
        'slug': 'cpu-cooler-2500-rpm',
        'priority': 4,
        'seo_title': '2500 RPM CPU Coolers at HiFi Computer',
        'description': 'Discover high-performance CPU coolers running at 2500 RPM for efficient cooling.',
        'cat_type': 'tag',
    },
]

fan_height = [
    {
        'title': '80mm',
        'slug': 'height-80mm-cpu-cooler',
        'priority': 4,
        'seo_title': '80 mm CPU Coolers at HiFi Computer',
        'description': 'Find CPU coolers with a height of 80 mm for compact builds.',
        'cat_type': 'tag',
    },
    {
        'title': '92mm',
        'slug': 'height-92mm-cpu-cooler',
        'priority': 4,
        'seo_title': '92 mm CPU Coolers at HiFi Computer',
        'description': 'Explore CPU coolers with a height of 92 mm for effective cooling in small form factors.',
        'cat_type': 'tag',
    },
    {
        'title': '100mm',
        'slug': 'height-100mm-cpu-cooler',
        'priority': 4,
        'seo_title': '100 mm CPU Coolers at HiFi Computer',
        'description': 'Discover CPU coolers that measure 100 mm in height, balancing size and performance.',
        'cat_type': 'tag',
    },
    {
        'title': '110mm',
        'slug': 'height-110mm-cpu-cooler',
        'priority': 4,
        'seo_title': '110 mm CPU Coolers at HiFi Computer',
        'description': 'Browse CPU coolers with a height of 110 mm for reliable thermal management.',
        'cat_type': 'tag',
    },
    {
        'title': '120mm',
        'slug': 'height-120mm-cpu-cooler',
        'priority': 4,
        'seo_title': '120 mm CPU Coolers at HiFi Computer',
        'description': 'Find efficient CPU coolers that are 120 mm tall, ideal for various builds.',
        'cat_type': 'tag',
    },
    {
        'title': '136mm',
        'slug': 'height-136mm-cpu-cooler',
        'priority': 4,
        'seo_title': '136 mm CPU Coolers at HiFi Computer',
        'description': 'Explore CPU coolers with a height of 136 mm for enhanced cooling capabilities.',
        'cat_type': 'tag',
    },
    {
        'title': '140mm',
        'slug': 'height-140mm-cpu-cooler',
        'priority': 4,
        'seo_title': '140 mm CPU Coolers at HiFi Computer',
        'description': 'Discover 140 mm CPU coolers that offer superior airflow and quiet operation.',
        'cat_type': 'tag',
    },
    {
        'title': '360mm',
        'slug': 'height-360mm-cpu-cooler',
        'priority': 4,
        'seo_title': '360 mm CPU Coolers at HiFi Computer',
        'description': 'Browse high-performance CPU coolers with a height of 360 mm for extreme cooling needs.',
        'cat_type': 'tag',
    },
]

cpu_cooler_colors = [
    {
        'title': 'Black',
        'slug': 'black-cpu-cooler',
        'priority': 4,
        'seo_title': 'Black CPU Coolers at HiFi Computer',
        'description': 'Explore our selection of black CPU coolers, designed for sleek aesthetics and performance.',
        'cat_type': 'tag',
    },
    {
        'title': 'Black and Silver',
        'slug': 'black-and-silver-cpu-cooler',
        'priority': 4,
        'seo_title': 'Black and Silver CPU Coolers at HiFi Computer',
        'description': 'Discover black and silver CPU coolers that blend style with efficiency.',
        'cat_type': 'tag',
    },
    {
        'title': 'Grey',
        'slug': 'grey-cpu-cooler',
        'priority': 4,
        'seo_title': 'Grey CPU Coolers at HiFi Computer',
        'description': 'Find grey CPU coolers that offer a modern touch to your build while ensuring optimal cooling.',
        'cat_type': 'tag',
    },
    {
        'title': 'Pink',
        'slug': 'pink-cpu-cooler',
        'priority': 4,
        'seo_title': 'Pink CPU Coolers at HiFi Computer',
        'description': 'Browse our unique collection of pink CPU coolers for a pop of color in your setup.',
        'cat_type': 'tag',
    },
    {
        'title': 'Silver',
        'slug': 'silver-cpu-cooler',
        'priority': 4,
        'seo_title': 'Silver CPU Coolers at HiFi Computer',
        'description': 'Explore stylish silver CPU coolers that provide great performance and aesthetic appeal.',
        'cat_type': 'tag',
    },
    {
        'title': 'White',
        'slug': 'white-cpu-cooler',
        'priority': 4,
        'seo_title': 'White CPU Coolers at HiFi Computer',
        'description': 'Discover white CPU coolers designed to complement your build with a clean and elegant look.',
        'cat_type': 'tag',
    },
]


CPU_COOLER_CATEGORIES = [
    *cpu_cooler_brands,
    *cpu_cooler_types,
    *supported_cpu_socket_brand,
    *fan_speed,
    *fan_height,
    *cpu_cooler_colors,
]

CPU_COOLER_GROUPS = [
    {
        'title': 'Cooler Type',
        'slug': 'cpu-cooler-types',
        'priority': 10
    },
    {
        'title': 'CPU Socket Brands',
        'slug': 'cpu-cooler-cpu-socket-brands',
        'priority': 9
    },
    {
        'title': 'Fan Speed',
        'slug': 'cpu-cooler-fan-speed',
        'priority': 8
    },
    {
        'title': 'Height',
        'slug': 'cpu-cooler-height',
        'priority': 8
    },
    {
        'title': 'Color',
        'slug': 'cpu-cooler-color',
        'priority': 7
    }
]
