processor_brands = [
    {
        'title': 'Intel',
        'slug': 'intel-processor',
        'priority': 5,
        'cat_type': 'brand',
        'seo_title': 'Intel Processors at HiFi Computer',
        'description': 'Intel Processors deliver cutting-edge performance and efficiency, ideal for gamers, creators, and professionals. Discover Intel CPUs at HiFi Computer in Bangladesh for unmatched speed and reliability in your computing tasks.'
    },
    {
        'title': 'AMD',
        'slug': 'amd-processor',
        'priority': 5,
        'cat_type': 'brand',
        'seo_title': 'AMD Processors at HiFi Computer',
        'description': 'AMD Processors provide exceptional performance and value, perfect for gaming, content creation, and multitasking. Explore AMD CPUs at HiFi Computer in Bangladesh for high-performance solutions that meet your computing needs.'
    },
]

processor_type = [
    {
        'title': 'Core i3',
        'slug': 'core-i3-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'Core i3 Processor at HiFi Computer',
    },
    {
        'title': 'Core i5',
        'slug': 'core-i5-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'Core i5 Processor at HiFi Computer',
    },
    {
        'title': 'Core i7',
        'slug': 'core-i7-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'Core i7 Processor at HiFi Computer',
    },
    {
        'title': 'Core i9',
        'slug': 'core-i9-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'Core i9 Processor at HiFi Computer',
    },
    {
        'title': 'Ryzen 3',
        'slug': 'ryzen-3-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'Ryzen 3 Processor at HiFi Computer',
    },
    {
        'title': 'Ryzen 5',
        'slug': 'ryzen-5-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'Ryzen 5 Processor at HiFi Computer',
    },
    {
        'title': 'Ryzen 7',
        'slug': 'ryzen-7-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'Ryzen 7 Processor at HiFi Computer',
    },
    {
        'title': 'Ryzen 9',
        'slug': 'ryzen-9-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'Ryzen 9 Processor at HiFi Computer',
    },
]

processor_generation = [
    {
        'title': '10th',
        'slug': '10th-gen-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '10th Gen Processor at HiFi Computer',
    },
    {
        'title': '11th',
        'slug': '11th-gen-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '11th Gen Processor at HiFi Computer',
    },
    {
        'title': '12th',
        'slug': '12th-gen-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '12th Gen Processor at HiFi Computer',
    },
    {
        'title': '13th',
        'slug': '13th-gen-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '13th Gen Processor at HiFi Computer',
    },
    {
        'title': '14th',
        'slug': '14th-gen-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '14th Gen Processor at HiFi Computer',
    },
]

processor_series = [
    {
        'title': '3000',
        'slug': '3000-series-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'Ryzen 3000 Processor at HiFi Computer',
    },
    {
        'title': '5000',
        'slug': '5000-series-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'Ryzen 5000 Processor at HiFi Computer',
    },
    {
        'title': '7000',
        'slug': '7000-series-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'Ryzen 7000 Processor at HiFi Computer',
    },
    {
        'title': '8000',
        'slug': '8000-series-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'Ryzen 8000 Processor at HiFi Computer',
    },
    {
        'title': '9000',
        'slug': '9000-series-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'Ryzen 9000 Processor at HiFi Computer',
    },
]

processor_base_frequency = [
    {
        'title': '2.10 GHz',
        'slug': '2.10GHz-base-freq-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '2.10 GHz Base Frequency Processor at HiFi Computer',
    },
    {
        'title': '2.50 GHz',
        'slug': '2.50GHz-base-freq-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '2.50 GHz Base Frequency Processor at HiFi Computer',
    },
    {
        'title': '2.60 GHz',
        'slug': '2.60GHz-base-freq-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '2.60 GHz Base Frequency Processor at HiFi Computer',
    },
    {
        'title': '2.90 GHz',
        'slug': '2.90GHz-base-freq-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '2.90 GHz Base Frequency Processor at HiFi Computer',
    },
    {
        'title': '3.00 GHz',
        'slug': '3.00GHz-base-freq-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '3.00 GHz Base Frequency Processor at HiFi Computer',
    },
    {
        'title': '3.06 GHz',
        'slug': '3.06GHz-base-freq-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '3.06 GHz Base Frequency Processor at HiFi Computer',
    },
    {
        'title': '3.40 GHz',
        'slug': '3.40GHz-base-freq-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '3.40 GHz Base Frequency Processor at HiFi Computer',
    },
    {
        'title': '3.50 GHz',
        'slug': '3.50GHz-base-freq-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '3.50 GHz Base Frequency Processor at HiFi Computer',
    },
    {
        'title': '3.60 GHz',
        'slug': '3.60GHz-base-freq-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '3.60 GHz Base Frequency Processor at HiFi Computer',
    },
    {
        'title': '3.70 GHz',
        'slug': '3.70GHz-base-freq-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '3.70 GHz Base Frequency Processor at HiFi Computer',
    },
    {
        'title': '3.80 GHz',
        'slug': '3.80GHz-base-freq-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '3.80 GHz Base Frequency Processor at HiFi Computer',
    },
    {
        'title': '3.90 GHz',
        'slug': '3.90GHz-base-freq-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '3.90 GHz Base Frequency Processor at HiFi Computer',
    },
    {
        'title': '4.20 GHz',
        'slug': '4.20GHz-base-freq-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '4.20 GHz Base Frequency Processor at HiFi Computer',
    },
    {
        'title': '4.30 GHz',
        'slug': '4.30GHz-base-freq-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '4.30 GHz Base Frequency Processor at HiFi Computer',
    },
    {
        'title': '4.50 GHz',
        'slug': '4.50GHz-base-freq-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '4.50 GHz Base Frequency Processor at HiFi Computer',
    },
    {
        'title': '4.70 GHz',
        'slug': '4.70GHz-base-freq-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '4.70 GHz Base Frequency Processor at HiFi Computer',
    },
]

processor_cores = [
    {
        'title': '4',
        'slug': '4-core-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '4 Core Processor at HiFi Computer',
    },
    {
        'title': '6',
        'slug': '6-core-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '6 Core Processor at HiFi Computer',
    },
    {
        'title': '8',
        'slug': '8-core-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '8 Core Processor at HiFi Computer',
    },
    {
        'title': '10',
        'slug': '10-core-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '10 Core Processor at HiFi Computer',
    },
    {
        'title': '12',
        'slug': '12-core-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '12 Core Processor at HiFi Computer',
    },
    {
        'title': '14',
        'slug': '14-core-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '14 Core Processor at HiFi Computer',
    },
    {
        'title': '16',
        'slug': '16-core-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '16 Core Processor at HiFi Computer',
    },
    {
        'title': '20',
        'slug': '20-core-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '20 Core Processor at HiFi Computer',
    },
    {
        'title': '24',
        'slug': '24-core-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '24 Core Processor at HiFi Computer',
    },
]

processor_threads = [
    {
        'title': '8',
        'slug': '8-thread-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '8 Thread Processor at HiFi Computer',
    },
    {
        'title': '12',
        'slug': '12-thread-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '12 Thread Processor at HiFi Computer',
    },
    {
        'title': '16',
        'slug': '16-thread-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '16 Thread Processor at HiFi Computer',
    },
    {
        'title': '20',
        'slug': '20-thread-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '20 Thread Processor at HiFi Computer',
    },
    {
        'title': '24',
        'slug': '24-thread-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '24 Thread Processor at HiFi Computer',
    },
    {
        'title': '28',
        'slug': '28-thread-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '28 Thread Processor at HiFi Computer',
    },
    {
        'title': '32',
        'slug': '32-thread-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '32 Thread Processor at HiFi Computer',
    },
]

processor_caches = [
    {
        'title': '6mb',
        'slug': '6mb-cpu-cache',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '6MB CPU Cache at HiFi Computer',
    },
    {
        'title': '12mb',
        'slug': '12mb-cpu-cache',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '12MB CPU Cache at HiFi Computer',
    },
    {
        'title': '16mb',
        'slug': '16mb-cpu-cache',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '16MB CPU Cache at HiFi Computer',
    },
    {
        'title': '18mb',
        'slug': '18mb-cpu-cache',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '18MB CPU Cache at HiFi Computer',
    },
    {
        'title': '19mb',
        'slug': '19mb-cpu-cache',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '19MB CPU Cache at HiFi Computer',
    },
    {
        'title': '20mb',
        'slug': '20mb-cpu-cache',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '20MB CPU Cache at HiFi Computer',
    },
    {
        'title': '22mb',
        'slug': '22mb-cpu-cache',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '22MB CPU Cache at HiFi Computer',
    },
    {
        'title': '24mb',
        'slug': '24mb-cpu-cache',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '24MB CPU Cache at HiFi Computer',
    },
    {
        'title': '25mb',
        'slug': '25mb-cpu-cache',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '25MB CPU Cache at HiFi Computer',
    },
    {
        'title': '30mb',
        'slug': '30mb-cpu-cache',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '30MB CPU Cache at HiFi Computer',
    },
    {
        'title': '33mb',
        'slug': '33mb-cpu-cache',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '33MB CPU Cache at HiFi Computer',
    },
    {
        'title': '35mb',
        'slug': '35mb-cpu-cache',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '35MB CPU Cache at HiFi Computer',
    },
    {
        'title': '36mb',
        'slug': '36mb-cpu-cache',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '36MB CPU Cache at HiFi Computer',
    },
    {
        'title': '38mb',
        'slug': '38mb-cpu-cache',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '38MB CPU Cache at HiFi Computer',
    },
    {
        'title': '40mb',
        'slug': '40mb-cpu-cache',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': '40MB CPU Cache at HiFi Computer',
    },
]

processor_sockets = [
    {
        'title': 'AM4',
        'slug': 'am4-socket-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'AM4 Socket Processor at HiFi Computer',
    },
    {
        'title': 'AM5',
        'slug': 'am5-socket-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'AM5 Socket Processor at HiFi Computer',
    },
    {
        'title': 'LGA1200',
        'slug': 'lga1200-socket-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'LGA1200 Socket Processor at HiFi Computer',
    },
    {
        'title': 'LGA1700',
        'slug': 'lga1700-socket-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'LGA1700 Socket Processor at HiFi Computer',
    },
    {
        'title': 'TR4',
        'slug': 'tr4-socket-processor',
        'priority': 5,
        'cat_type': 'tag',
        'seo_title': 'TR4 Socket Processor at HiFi Computer',
    },
]

PROCESSOR_CATEGORIES =[
    *processor_brands,
    *processor_type,
    *processor_generation,
    *processor_series,
    *processor_base_frequency,
    *processor_cores,
    *processor_threads,
    *processor_caches,
    *processor_sockets,
]

PROCESSOR_GROUPS = [
    {
        'title': 'Processor Type',
        'slug': 'processor-type',
        'priority': 4,
    },
    {
        'title': 'Generation',
        'slug': 'processor-generation',
        'priority': 4,
    },
    {
        'title': 'Series',
        'slug': 'processor-series',
        'priority': 4,
    },
    {
        'title': 'Base Frequency',
        'slug': 'processor-base-frequency',
        'priority': 4,
    },
    {
        'title': 'Cores',
        'slug': 'processor-cores',
        'priority': 4,
    },
    {
        'title': 'Threads',
        'slug': 'processor-threads',
        'priority': 4,
    },
    {
        'title': 'Cache',
        'slug': 'processor-caches',
        'priority': 4,
    },
    {
        'title': 'Socket',
        'slug': 'processor-sockets',
        'priority': 4,
    },
]
